### ISSUE TITLE
ModuleNotFoundError: No module named 'cyberbattle'

### ISSUE THREAD

**Issue by stwater20** [microsoft/CyberBattleSim#102]
When I call
```
docker run -it -v "$(pwd)":/source --rm cyberbattle:1.1 /bin/bash
```

```
python cyberbattle/agents/baseline/run.py --training_episode_count 5 --eval_episode_count 3 --iteration_count 100 --rewardplot_width 80  --chain_size=4 --ownership_goal 0.2
```
The output is 
```
ModuleNotFoundError: No module named 'cyberbattle'
```
But using Ipython, it is normal.

**Comment by 2twentytwo2** [comment]
您好，您的邮件我已收到，
看到后，我会立即回复您。
This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by stwater20** [comment]
Finally,
I use 
```
export PYTHONPATH=$PYTHONPATH:/root/cyberbattle
```
In the environment, then it will be successful.

<img width="777" alt="image" src="https://user-images.githubusercontent.com/50062014/236381462-6528c3f2-8d38-4712-96c1-8162f28d12a4.png">
