### ISSUE TITLE
Key for how the simulation is working

### ISSUE THREAD

**Issue by Beauxrel** [microsoft/CyberBattleSim#107]
I am new to this sort of content and am struggling to know the difference between 'owned' and 'discovered'. To add to this, I want to increase the nodes/networks the attacker has to traverse through before it gets a reward. I believe it is a matter of adding more nodes like this for example.

"Website.Directory": m.NodeInfo(
        services=[m.ListeningService("HTTPS")],
        value=50,
        properties=["Ubuntu", "nginx/1.10.3",
                    "CTFFLAG:Readme.txt-Discover secret data"
                    ],
        vulnerabilities=dict(
            NavigateWebDirectoryFurther=m.VulnerabilityInfo(
                description="Discover MYSQL credentials MySql for user "
                            "'web' in (getting-started.txt)",
                type=m.VulnerabilityType.REMOTE,
                outcome=m.LeakedCredentials(credentials=[
                    m.CachedCredential(node="Website", port="MySQL",
                                       credential="ReusedMySqlCred-web")]),
                reward_string="Discover browseable web directory: Navigating to parent URL revealed file `readme.txt`"
                              "with secret data (aflag); and `getting-started.txt` with MYSQL credentials",
                cost=1.0
            ),
            NavigateWebDirectory=m.VulnerabilityInfo(
                description="Discover URL to external sharepoint website "
                            "(in deprecation-checklist.txt)",
                type=m.VulnerabilityType.REMOTE,
                outcome=m.LeakedNodesId(["Sharepoint"]),
                reward_string="Navigating to parent URL revealed file `deprecation-checklist.txt` containing"
                              "a URL to an external sharepoint website",
                cost=1.0
            )
        )),

**Comment by blumu** [comment]
Yes, you can just add more nodes to the network as you described in your question.

- `discovered` means that the attacker knows about the endpoint/machine/server, and it can refer to it in subsequent actions (e.g., attempting to connect to it)
- `owned` means that it has full access to the machine and can run actions from that machine. e.g. attempt connections from that machine to other machines.
