### ISSUE TITLE
simplenv bidirectional?

### ISSUE THREAD

**Issue by Beauxrel** [microsoft/CyberBattleSim#109]
In simpleenv.py are the edges created bidirectional? I'm trying to make a tree network but am unsure if create an edge from one node to another covers that edge in both directions.

**Comment by Beauxrel** [comment]
My concern comes from my e node looking lonely without an edge, but d -> e should cover that? 


network: &id019 !!python/object:networkx.classes.digraph.DiGraph
  _adj: &id018
    a:
      b: &id005 {}
      c: &id006 {}
      d: &id008 {}
    b:
      c: &id007 {}
      d: &id009 {}
    c:
      d: &id010 {}
    d:
      e: &id011 {}
    e: {}
    f:
      e: &id012 {}
      g: &id015 {}
      h: &id016 {}
    g:
      e: &id013 {}
      h: &id017 {}
    h:
      e: &id014 {}
  _node: &id020

**Comment by blumu** [comment]
It's a digraph (`DiGraph`) so the edges are _not_ bidirectional.

**Comment by Beauxrel** [comment]
Thank you! That is helpful. Is bidirectionality even possible? I assume I would need to initialize them back and forth for that sort of functionality.
