### ISSUE TITLE
python 3.11 not working - ValueError: mutable default <class 'cyberbattle.simulation.model.FirewallConfiguration'>

### ISSUE THREAD

**Issue by Beauxrel** [microsoft/CyberBattleSim#111]
Change env.yml 
python>=3.9
should be
python=3.9

**Comment by blumu** [comment]
Could you share the error you get with 3.11?

**Comment by Beauxrel** [comment]
File "/home/landon/miniconda3/envs/cybersim/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'cyberbattle.simulation.model.FirewallConfiguration'> for field firewall is not allowed: use default_factory

**Comment by Beauxrel** [comment]
Off-topic, but is there a way to save checkpoints of my learning? would like to train models and pick back up later.

**Comment by Beauxrel** [comment]
@blumu

**Comment by Beauxrel** [comment]
```
all_runs.append(dqn_learning_run)

new_array = np.array(all_runs)
file = open("/home/landon/Desktop/sample.txt", "x")
content = str(new_array)
file.write(content)
file.close()
```

here I am saving all_runs array as a text file. Could I just feed this back into the next run to pickup where I left off?

**Comment by virenderdhiman** [comment]
I am getting the same issue mentioned above when I try to clone and run the test with following command "python -m cyberbattle.agents.baseline.run --training_episode_count 5 --eval_episode_count 3 --iteration_count 100 --rewardplot_width 80  --chain_size=4 --ownership_goal 0.2
Issue:

File "/home/landon/miniconda3/envs/cybersim/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'cyberbattle.simulation.model.FirewallConfiguration'> for field firewall is not allowed: use default_factory

Can someone provide the resolution for this?

**Comment by 2twentytwo2** [comment]
您好，您的邮件我已收到，
看到后，我会立即回复您。
This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by Beauxrel** [comment]
@virenderdhiman the solution is to install with the python change in env.yml, 3.11 will not work.

**Comment by blumu** [comment]
Reopening until the python version gets fixed in env.yaml
