### ISSUE TITLE
Migration to Gymnasium

### ISSUE THREAD

**Issue by raphsimon** [microsoft/CyberBattleSim#132]
Hello,

are there any plans on migrating from the OpenAI gym interface to the gymnasium interface?

Best,
Raph

**Comment by blumu** [comment]
Yes, we will soon upgrade to gym 0.26 which should make the final migration to gymnasium much easier.

**Comment by blumu** [comment]
PR https://github.com/microsoft/CyberBattleSim/pull/144 addresses this feature request. @raphsimon Give it a try and let us know if it works for you.
