### ISSUE TITLE
ModuleNotFound 

### ISSUE THREAD

**Issue by Ascrypto** [microsoft/CyberBattleSim#32]
I had this issue when I tried to run the simulation. 
"No module named 'cyberbattle'."
I tried to export the path but did not work.

**Comment by ezioyan** [comment]
I added the directory to the system path and it worked:
`import sys`
`sys.path.insert(0, 'path')`

**Comment by Ascrypto** [comment]
Thanks for pointing me in the right direction. For some reason, it did not work with insert(), but worked just fine with sys.path.append().
