### ISSUE TITLE
Failed when using init.sh

### ISSUE THREAD

**Issue by syheliel** [microsoft/CyberBattleSim#40]
![image](https://user-images.githubusercontent.com/45957390/142408254-eb7edd76-58cd-427a-813a-f5e1eec8f0fc.png)

**Comment by syheliel** [comment]
I think that it's better to use `./init.sh` to setup the environment in `.github/workflows/ci.yml` so that the script can be test every commit.

**Comment by blumu** [comment]
@syheliel Line 2 indicates a permission issue. Could this be due to the permissions set for that directory? Or does this repro if you clone the repo in a new fresh directory? Also did you pass any parameter to `init.sh` and have you tried running it with `sudo`?

**Comment by blumu** [comment]
I could not repro the reported permission issue, but I've changed ci.yml to call `init.sh` as suggested above and the script runs fine under Github Actions. I am closing the issue. @syheliel Feel free to reopen and share the full logs if you still hit this issue.
