### ISSUE TITLE
unable to run toyctf.ipynb interactive 

### ISSUE THREAD

**Issue by fcheong283** [microsoft/CyberBattleSim#45]
I try running the first cell and receive the error ModuleNotFoundError: No module named 'cyberbattle'

**Comment by phypoh** [comment]
Not the official answer, but I think there's two ways you can solve this:

1) Add the cyberbattle folder to your path in your notebook (it's located in the root directory of the repo) 
2) Run `pip3 install -e CyberBattleSim` one folder outside the repo.

**Comment by fcheong283** [comment]
Thank you for this! The second option seemed to fix it however I now run into another error on cell 15. The ValueError says 'mime type rendering requires nbformat>=4.2.0 but it is not installed' Even though I had 4.4.0 installed. I upgraded to 5.1.3 however the error still occurs. Any ideas?

**Comment by blumu** [comment]
@fcheong283 You want to run the `init.sh` script first to install all the required components.
For the second error you get, have you tried reinstalling `ipykernel` as suggested at https://stackoverflow.com/questions/66557543/valueerror-mime-type-rendering-requires-nbformat-4-2-0-but-it-is-not-installed ?

**Comment by fcheong283** [comment]
I have tried running the init.sh script however there's a syntax error in line 6:

 pushd "$(dirname "$0")"
          ^
SyntaxError: invalid syntax

**Comment by blumu** [comment]
@fcheong283 Which shell are you using? Have you tried running it under the `bash` shell?

**Comment by blumu** [comment]
@fcheong283 I am closing it for now. Please try running the init.sh script from a Linux bash shell. If that stills reproes you can reopen the issue and share your logs/errors.
