### ISSUE TITLE
Maximum number of iterations per episode

### ISSUE THREAD

**Issue by ammohamedds** [microsoft/CyberBattleSim#69]
Hello: Thanks for this interesting and beneficial tool
In case of
iteration_count = 150 (for example)  and gymid = "CyberBattleTiny-v0"

I found that sometimes while implementing your DQL agent ,and my customized DQL and other agents. The maximum number of iterations in each episode is not 150 iterations for my agents, while when I implement your DQN agent, I find that the iterations are always 150 (the maximum iteration). Even though the cumulative reward is almost the same and performance is comparable. Also, although I'm using almost the same code except for some changes in online and target networks.

Is there a problem in my agents?
What is the attacker's target of capturing the flag in the CyberBattle tool: is it just to own the nodes or must complete all iterations as well along with owning the nodes.
Thanks

**Comment by blumu** [comment]
The total number of simulated iterations depends on the target goal configured for the attacker and defender. As soon as the goal is reached the simulation gets terminated. Take a look here for examples on how to set the target goal when registering the gym environment:

https://github.com/microsoft/CyberBattleSim/blob/139598bec623e568a742e5b93658da7f162bb667/cyberbattle/__init__.py#L88

See documentation of the parameter here:
https://github.com/microsoft/CyberBattleSim/blob/ac96d7bfa7bb294efb8f192d50d8eff8a8ce877b/cyberbattle/_env/cyberbattle_env.py#L403

Setting the goal to `None` will run the simulation until the maximum number of iterations is reached.

**Comment by blumu** [comment]
@ammohamedds I am closing this issue for now. Feel free to reopen if the answer above does not address your question.
