### ISSUE TITLE
install in WSL fails due to missing dependency

### ISSUE THREAD

**Issue by bwanaaa** [microsoft/CyberBattleSim#8]
virgin WSL w ubuntu 20.04 LTS

init.sh gives

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.

**Comment by blumu** [comment]
@bwanaaa  Could you share the full stdout/stderr output?

**Comment by blumu** [comment]
@bwanaaa Closing the issue for now. A few setup issues were resolved recently. If you still hit this issue on the latest version of the `main` branch please feel free to reopen and share the logs of `init.sh`. Thank you!
