### ISSUE TITLE
Jupyter notebook run issue from docker container

### ISSUE THREAD

**Issue by kvas7andy** [microsoft/CyberBattleSim#89]
Hi all,

I have encountered issue when running jupyter notebook inside docker container. While forwarding the port from docker container, I still cannot connect to it from browser. It does not work both on local machine and remote server I use.

Sample command is:

```
git clone https://github.com/microsoft/CyberBattleSim.git
cd CyberBattleSim
nvidia-docker build -t cyberbattle:1.1 .
nvidia-docker run -p 6789:8888 -it --name cyber_test cyberbattle:1.1 /bin/bash -c "jupyter notebook --no-browser --allow-root --port=8888"

[browser] localhost:6789
[Error] "Hmmm… can't reach this page\n Localhost refused to connect.
```

**Comment by blumu** [comment]
Are you using remote development into WSL or SSH from VSCode? If so you may want to try adding the port redirections manually in VSCode under the 'Ports' tab. I used to have the same problem and that fixed it for me.

**Comment by kvas7andy** [comment]
I am using VSCode and your workaround seems working for me also. I was thinking, that because standard way is to redirect port form container with `nvidia-docker run -p` other users of simulator may have issues in working with docker container, so I wanted to mention this issue for reference.

Did you find the source of the issue? Does that mean there is any restriction on port forwarding made with Dockerfile or during `init.sh`?
