### ISSUE TITLE
Making reward non-zero, what is the reason?

### ISSUE THREAD

**Issue by kvas7andy** [microsoft/CyberBattleSim#94]
Checking the code and why there is no negative reward due to penalties or repetition I have noticed, that code `reward = max(0., reward)` makes it always non-zero [here](https://github.com/microsoft/CyberBattleSim/blob/4fd228bccfc2b088d911e27072a923251203cac8/cyberbattle/_env/cyberbattle_env.py#L1121).

What was the reason to make all rewards non-zero?

**Comment by blumu** [comment]
This was a recommendation from RL experts. It was suggested that negative rewards could prevent convergence for some RL algorithms. We could make this configurable. Let us know if you have examples showing better results without the clipping.
