### ISSUE TITLE
Something wrong with the node's last owned time and last reimaged time?

### ISSUE THREAD

**Issue by Catalpae** [microsoft/CyberBattleSim#95]
Sorry to bother.

I am wondering if class **NodeTrackingInformation** is not indicating the right occurrence time of the last attack?

The **time()** func at line 248 and 671 in actions.py would set the nodes's **last_reimaging_time** and **last_owned** time to be '00:00:00'. So when the cyber attacker attempts to re-connect to a conquered but lately reimaged node, func **__is_node_owned_history** at line 483 would recognize the reimaged node as a currently owned node. Therefore the cyber attacker can never connect to a reimaged node successfully.

Is it true, or am I mistaking something here😂?

**Comment by blumu** [comment]
Thanks for reporting. That's a bug where the action.py file imports the `time` _module_ with `from datetime import time` instead of importing the `time` function using `from time import time`. Testing a fix, will submit a PR soon
