### ISSUE TITLE
How to setup machine/program for use

### ISSUE THREAD

**Issue by ko19af** [microsoft/CyberBattleSim#99]
Hello, Is there a video or FAQ page or more detailed guide about how to setup my machine and how to run the software for use, I am having issues getting the program to work as some of the commands outlined are not working for me such as the ./init.sh file is not downloading all of the dependencies to my machine.

I greatly appreciate the help.

**Comment by blumu** [comment]
@ko19af The best place to start is the "Getting started quickly with docker" section from the README and use docker to build a container image:
https://github.com/microsoft/CyberBattleSim#getting-started-quickly-using-docker
```
docker build -t cyberbattle:1.1 .
docker run -it -v "$(pwd)":/source --rm cyberbattle:1.1 cyberbattle/agents/baseline/run.py

**Comment by Reihold-Chen** [comment]
i meet the problem when i build the docker image：
```
 => [3/8] ADD *.sh ./                                                                                                                                      0.1s
 => [4/8] ADD *.txt ./                                                                                                                                     0.1s
 => [5/8] ADD *.py ./                                                                                                                                      0.1s
 => ERROR [6/8] RUN export TERM=dumb && ./init.sh -n   
......
......
#10 13.24 + add-apt-repository ppa:deadsnakes/ppa -y
#10 27.35 Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
#10 27.44 Get:2 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease [15.9 kB]
.......
#10 68.53 Get:21 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [20.6 kB]
#10 68.54 Fetched 16.3 MB in 42s (387 kB/s)
#10 68.54 Reading package lists...
#10 69.54 + apt update
......
#10 241.7 Reading state information...
#10 241.9 E: Unable to locate package python3.9
#10 241.9 E: Couldn't find any package by glob 'python3.9'
#10 241.9 E: Couldn't find any package by regex 'python3.9'
#10 241.9 E: Unable to locate package python3.9-distutils
#10 241.9 E: Couldn't find any package by glob 'python3.9-distutils'
#10 241.9 E: Couldn't find any package by regex 'python3.9-distutils'
#10 241.9 E: Unable to locate package python3.9-dev
#10 241.9 E: Couldn't find any package by glob 'python3.9-dev'
#10 241.9 E: Couldn't find any package by regex 'python3.9-dev'
```

[ppa:deadsnakes/ppa](https://github.com/deadsnakes/issues/issues/251)  announce that packages are deleted from deadsnakes once a distribution version reaches end-of-life in

ubuntu bionic 18.04 has just reached end-of-life and as such its packages will be deleted

it seem that we should update the `init.sh` script or use the newer ubuntu basic image

**Comment by 2twentytwo2** [comment]
您好，您的邮件我已收到，
看到后，我会立即回复您。
This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by ean8742** [comment]
I am also facing this issue when trying to follow "Getting started quickly with docker." Any guidance/updated scripts would be greatly appreciated.

**Comment by blumu** [comment]
@ean8742 @2twentytwo2 @Reihold-Chen The problem with the deadsnakes repo is covered in #104. Somebody offered a possible mitigation in there. The issue was closed but I have reopened it and will keep it open until we have a fix merged in main. I will close this less-specific issue for now.
